### ISSUE TITLE
Support for Sass variables and documenting BEM/OOCSS hierarchy/relationships

### ISSUE THREAD

**Issue by alademann** [SassDoc/sassdoc#15]
Hugo...

I'm curious if it would be possible to support non-mixin/function documentation? I'm needing something like http://sassdocjs.com/doc/, but [that repo](https://github.com/mattbieber/sassdocjs)'s code is borderline un-maintainable IMO.

The function and mixin parsing is awesome - and I need that piece.  But in order to document a modular front-end framework built with Sass, there are a few more pieces to the puzzle for me. (These are all just suggestions / open for discussion obviously)

First thing is... I need a way to document some basic Sass `$variables` _(and maybe event some nifty Sass map-typed variable traversal)_.

I also need to document / describe relationships / dependencies between Sass entities _(classes, placeholders, ids, etc...)_ and entire modules _(read: Sass partials)_ in a very large, very modular BEM/OOCSS platform.

I would propose adding the following definitions _(I also understand if this needs to be broken into separate issues, but wanted to get a discussion rolling in one place)_:

**Variables**
- `@var {type | other type} $name (default value) - description of var` 
  - I'm assuming combining this with something like `@private` means that it is scoped to a module, and combined with `@public` means that it would be declared using `!global`?
  - Vars would need to be able to declare dependencies on other vars / modules containing vars (see example `$panel` var below)

**Meta**
- `@example` - provide brief HTML implementation example
- `@usedin` - similar to `@link` - provide an example where a developer could see it being used
- `@since` - provide a version when a specific class/function/mixin was made available
- `@support` - list of supported browsers for a module

**Modular (BEM/OOCSS) Hierarchy**
- `@module` - define a file as a module.
  - `@base` - define a class/id as a "base" class/id for a module.
    - `@element` - define a class/id as a "element" class/id for a "base" class/id
    - `@modifier {type}` - define a class/id as a "modifier" class/id for a "base" _or_ "element" class/id
      - The `{type}` would be "open-ended", but would be something like `variant` or `state`, for example.
- `@depends` - similar to `@requires` - except this would create a link to an external `@module` _(or even some JS)_ that is not implied via the declared `@base`/`@element`/`@modifier` syntax.
  -  _allow multiple via comma-separated list - or multiple `@depends` lines (see `$panel` var example below)?_
- `@extends` - similar to `@depends`, but this type of element would automatically extend a dependency instead of implying that the other module/component had to be used/included separately.

---
## Example

Below is an example "module" - in a platform that shows a little bit of what I'm envisioning / describing above.
- This file would be located in a taxonomy such as `sass/core/modules/_panels.scss`.

``` scss
// ---------------------------------------------------------
// @module core/modules/panels
// --- 
// Flexible containers that help to isolate/provide context 
// to other core elements in the platform.
// ---
// @since 0.2.1
// ---
// @example
//   <div class="panel panel-default">
//     <div class="panel-heading">
//       <h3 class="panel-title">Panel title</h3>
//     </div>
//     <div class="panel-body">
//       Panel content
//     </div>
//     <div class="panel-footer">
//       Panel content
//     </div>
//   </div>
// ---
// @link http://mystyleguide.com/core/modules/panels
// ---------------------------------------------------------


// @private @var $panel {map} - stores configuration options for .panel module
// ---
// @since 0.5.0
// ---
// @depends core/config/defaults, core/config/colors
$panel: (
  'base': (
    'default': (
      'text': $gray-dark,
      'bg': #fff,
      'bd': #ddd 
    ),
    'success': (
      'text': $state-success-text,
      'bg': $state-success-bg,
      'bd': $state-success-bd
    )
  ),
  'body': (
    'padding': 15px
  ),
  'heading': (
    'padding': 10px 15px
  ),
  'footer': (
    'padding': 10px 15px
  )
) !default;


// @base panel
// ---
// Must be combined with one of the variant modifiers to gain styling.
.panel {
  foo: bar;
}

// @element panel-body
// ---
// Panel contents
.panel-body {
  foo: bar;
}

// @element panel-heading
// ---
// Optional heading above panel contents
// --
// @link http://mystyleguide.com/core/modules/panels-with-heading
.panel-heading {
  foo: bar;
}

// @element panel-title
// ---
// Within panel-heading, strip any `h*` tag of its default margins for spacing.
.panel-title {
  foo: bar;
}

// @element panel-footer
// ---
// Optional footer below panel contents
.panel-footer {
  foo: bar;
}

// @element panel>list-group
// ---
// List groups in panels
// ---
// @depends core/modules/list-groups
// ---
// @link http://mystyleguide.com/core/modules/panels-list-group
// ---
// @example
//   <div class="panel panel-default">
//     <!-- Default panel contents -->
//     <div class="panel-heading">Panel heading</div>
//     <div class="panel-body">...</div>
//   
//     <!-- List group -->
//     <ul class="list-group">
//       ...
//     </ul>
//   </div>
.panel > .list-group {
  foo: bar;
}

// @element panel>table
// ---
// Tables in panels
// ---
// @depends core/modules/tables
// ---
// @link http://mystyleguide.com/core/modules/panels-tables
// ---
// @example
//   <div class="panel panel-default">
//     <!-- Default panel contents -->
//     <div class="panel-heading">Panel heading</div>
//     <div class="panel-body">...</div>
//   
//     <!-- Table -->
//     <table class="table">
//       ...
//     </table>
//   </div>
.panel > .table {
  foo: bar;
}

// @modifier {variant} default
.panel-default {
    foo: bar;
}

// @modifier {variant} success
.panel-success {
  foo: bar;
}

// @modifier {size-variant} small
.panel-sm {
  foo: bar;
}

// @modifier {state} is-focused
// ---
// @depends js/modules/panels
.panel.is-focused {
    foo: bar;
}
```

---

Thanks so much for discussing/considering this - I'm happy to do whatever I can to contribute if you think these are valuable additions to the repo. Any other thoughts on how to make this more intuitive are most welcome and appreciated!
