### ISSUE TITLE
Placeholder support

### ISSUE THREAD

**Issue by callum** [SassDoc/sassdoc#154]
I would like to be able to document placeholders:

``` scss
/**
 * Standard clearfix
 */

%clearfix {
  overflow: hidden;
}
```

Doesn't look like it would be too difficult to implement.
