### ISSUE TITLE
Support Sass files

### ISSUE THREAD

**Issue by KittyGiraudel** [SassDoc/sassdoc#236]
Here is a function declaration...

... in SCSS:

``` scss
@function name($arg1, $arg2, $args...) {
  @return value;
}
```

... in Sass:

``` sass
@function name($arg1, $arg2, $args...)
  @return value
```

Here is a mixin declaration...

... in SCSS:

``` scss
@mixin name($arg1, $arg2, $args...) {
  property: value;
}
```

... in Sass:

``` sass
@mixin name($arg1, $arg2, $args...)
  property: value
```

Here is a variable declaration...

... in SCSS:

``` scss
$var: value;
```

.... in Sass:

``` sass
$var: value
```

Here is a placeholder declaration...

... in SCSS:

``` scss
%placeholder {
  property: value;
}
```

... in Sass:

``` sass
%placeholder
  property: value
```

I suppose there is very little to be done to support `.sass` files.
