### ISSUE TITLE
Bug with parenthesis inside default values

### ISSUE THREAD

**Issue by ben-eb** [SassDoc/sassdoc#303]
Given this example SCSS:

```scss
/**
 * Main colour palette.
 *
 * @prop {Color} main-background   (rgb(61, 75, 92))  - Deep, blueish gray
 *
 * @see {function} colour
 *
 * @type Map
 */
$colours: (
    "main-background": rgb(61, 75, 92)
);
```

I should expect that it outputs the colour correctly. However, I get an error:

```
[16:42:07] TypeError in plugin 'gulp-sassdoc'
Message:
    Cannot use 'in' operator to search for 'stack' in unknown color: rgb(61, 75, 92
```

Is it possible to add support for RGB(a) and HSL(a) values when documenting colours? :smile:
