### ISSUE TITLE
Try to infer default values when compiling

### ISSUE THREAD

**Issue by ben-eb** [SassDoc/sassdoc#304]
If I have some map, or mixin, with a documented property, it might be nice to try to parse the SCSS following the comment to try and infer its default value. Such that writing this SCSS:

```scss
/**
 * Main colour palette.
 *
 * @prop {Color} main-background - Deep, blueish gray
 *
 * @see {function} colour
 *
 * @type Map
 */
$colours: (
    "main-background": rgb(61, 75, 92)
);
```

Should be parsed exactly the same as if we were to explicitly write the default value:

```scss
/**
 * Main colour palette.
 *
 * @prop {Color} main-background (rgb(61, 75, 92)) - Deep, blueish gray
 *
 * @see {function} colour
 *
 * @type Map
 */
$colours: (
    "main-background": rgb(61, 75, 92)
);
```

The benefits of doing this - well, having documentation that is up to date is pretty important. I can see a few cases where an author will update their SCSS files, and forget to change a variable in the doclet. Would be a nice feature to have!
