### ISSUE TITLE
base-64 encoded images falsely being detected as poster comments

### ISSUE THREAD

**Issue by migstopheles** [SassDoc/sassdoc#331]
Example:

```scss
.my-icon {
    background: url(data:image/png;base64,blahblahblah////blahblah);
}
```

More than one of these per file causes `[WARNING] Error: You can't have more than one poster comment.` Docs are still being generated so this isn't a dealbreaker, but it's not desired behaviour.
