### ISSUE TITLE
Mixin with a property that's the same name causes an incorrect "Requires" output

### ISSUE THREAD

**Issue by ChrisUpjohn** [SassDoc/sassdoc#359]
I couldn't find anything on this one, essentially what's happening is the following for example.

```scss
@mixin position($position) {
  position: $position;
}
```

When SassDoc parses this it sees the property `position` as a requirement instead of looking ahead first and determining the type of execution thus it assumes `position` requires `position` even though it doesn't, to get around this for the time being I can prefix the mixin which doesn't bother me too much as seen below.

```scss
@mixin t-position($position) {
  position: $position;
}
```

SassDoc version: **2.0.3**
NPM version: **1.4.28**
