### ISSUE TITLE
Parsing comments on CSS classes

### ISSUE THREAD

**Issue by couellet** [SassDoc/sassdoc#452]
I have the following code:

```scss
///
/// Container for action step buttons
///
.snip-actions {
    border-top: $_action-border;
    padding: $padding-small;

    // [1]
    @include clearfix;

    /// Sets the padding for meidum or large screens
    @media #{$mq-medium} {
        padding: $_action-pad;
    }
}
```

I am trying to figure out a way to show the comment in the generated documentation. We are using BEM pattern and we'd like to document our components. We don't need anything fancy or overkill, just to be able to show the comments. Is there a configuration somewhere I am missing?

Thanks!
