### ISSUE TITLE
ability to have indented/nested annotations

### ISSUE THREAD

**Issue by esr360** [SassDoc/sassdoc#458]
I'm new to using SassDoc so perhaps I'm not quite using it right, as I'm finding myself requiring the ability to use nested annotations for things like private function variables. Here's an example:

```scss
/// Function to get desired font-size values
/// @access private
/// @group utilities
/// @param {map} $original-sizes - the original map of font-sizes
/// @param {list} $new-values - the keys you are interested in
/// @return {map} - new map containing only desired values
@function get-font-sizes($original-sizes, $new-values) {

    /// Get the keys of the desired new values
    ///
    /// @access private
    /// @type [map|list|string]
    $keys: if(type-of($new-values) == 'map',
        map-keys($new-values), $new-values
    );

    /// Remove the desired values from the original list
    ///
    /// @access private
    /// @type map
    $new-sizes: map-remove($original-sizes, $keys...);

    /// Now using the new list, we can remove those from the 
    /// original list to leave us with with our desired values
    ///
    /// @access private
    /// @type map
    $new-sizes: map-remove($original-sizes, map-keys($new-sizes)...);

    @return $new-sizes;

}
```

Am I wrong in wanting to have these things output in the documentation? I feel like it would be nice but currently the annotations are not registered due to the indentation. Apologies if this has already been discussed but I couldn't find anything other than [this post](https://github.com/SassDoc/sassdoc/issues/18#issuecomment-47259821).
