### ISSUE TITLE
Docs showing only the last documented mixin on page with more  that one mixins

### ISSUE THREAD

**Issue by vladyn** [SassDoc/sassdoc#483]
Hello there, 
first to say - you did great doc tool ! Really! 
I have question (or issue) where i created two mixins in one file (and I'm about to keep all in one file), but after the docs has been generated - I've got only the last mixing form the file : 

    ////
    /// Mixins.
    /// @group Ungrouped 
    /// @author CSI team
    ///
    /// Breakpoints
    /// This mixin gives you ability to include it in a css selector and make it behave different on triggered     screen sizes.
    /// @arg $point {type} String
    /// @param {String} $medium: ['(max-width: 1024px) and (min-width: 769px)'] - Screen size < 1024
    /// @param {String} $xlarge: ['(min-width: 1441px)'] - above 1440
    /// @param {String} $large-desktop-break: ['(max-width: 1280)'] - below 1280
    /// @param @content - passes the css rules you want to use in give screen resolution
    /// @example scss 
    /// .selector {
    ///     background-color: yellow;
    ///     @include breakpoint(medium) { background-color: red; }
    /// }
    /// // everrything above 1024 will have bg yellow and under - red;
    /// @group Mixins
    /// @author varbavl
    ///

    @mixin breakpoint($point) {
        @if $point == small {
            @media (max-width: 1024px) and (min-width: 769px) { 
                @content;
            }
        }
    ....
    }

    ///
    /// Mixin for adjusting the font-size
    /// @param {size} $size [10%] - size for font size adjusting. Could be negative as well as any valid unit.
    /// @example scss
    /// selector {
    ///     @include font-size(-25%);
    /// }
    /// @group ...
    /// @author vv
    ///
    @mixin font-size($size: 10%) {
       font-size: calc(100% + #{$size});
    }

Con somebody tell me what I'm doing wrong ?

**Comment by HugoGiraudel** [comment]
Hello.

I believe your problem lies on the fact that you are mixing file-annotations with single ones. IT should probably be:

```scss
////
/// Mixins.
/// @group Ungrouped 
/// @author CSI team
////


/// Breakpoints
/// This mixin gives you ability to include it in a css selector and make it behave different on triggered     screen sizes.
/// @arg $point {type} String
/// @param {String} $medium: ['(max-width: 1024px) and (min-width: 769px)'] - Screen size < 1024
/// @param {String} $xlarge: ['(min-width: 1441px)'] - above 1440
/// @param {String} $large-desktop-break: ['(max-width: 1280)'] - below 1280
/// @param @content - passes the css rules you want to use in give screen resolution
/// @example scss 
/// .selector {
///     background-color: yellow;
///     @include breakpoint(medium) { background-color: red; }
/// }
/// // everrything above 1024 will have bg yellow and under - red;
/// @group Mixins
/// @author varbavl
///

@mixin breakpoint($point) {
    @if $point == small {
        @media (max-width: 1024px) and (min-width: 769px) { 
            @content;
        }
    }
}

///
/// Mixin for adjusting the font-size
/// @param {size} $size [10%] - size for font size adjusting. Could be negative as well as any valid unit.
/// @example scss
/// selector {
///     @include font-size(-25%);
/// }
/// @group ...
/// @author vv
///
@mixin font-size($size: 10%) {
   font-size: calc(100% + #{$size});
}
```
